export const {
    NODE_ENV,
    DEV_SERVER_PORT,
    API_URL,
    CREQ,
    DEFAULT_LANGUAGE,
    ACS_TRANSACTION_ID,
    ERROR,
    ERROR_POP_UP_TIMEOUT_IN_MS,
    AUTHORIZATION_CODE_FROM_CIAM,
} = window.REACT_APP;

export const GENERAL_EXCEPTION_ERROR_CODE = 'GENERAL_EXCEPTION';
export const FATAL_EXCEPTION_ERROR_CODE = 'FATAL_EXCEPTION';
export const WRONG_APPLICATION_STATE_ERROR_CODE = 'WRONG_APPLICATION_STATE';
export const TRANSLATED_ERROR_ERROR_CODE = 'TRANSLATED_ERROR';

export const REQUEST_CANCELED_CODE = 'REQUEST_CANCELED';
