package com.bank.acs.enumeration;

public enum AppState {
    CHECK_CARD_STATUS,
    CARD_CHECK_SUCCESSFUL,

    RENDER_ENTER_LOGIN_PAGE,
    RENDER_SELECT_AUTH_METHOD_PAGE,
    RENDER_INIT_AUTH_PAGE,
    CHECKING_AUTH_STATUS,
    RENDER_SUCCESSFUL_PAGE,
    AUTHENTICATION_IN_PROGRESS,
    RENDER_FATAL_ERROR_PAGE,
    RENDER_NON_FATAL_ERROR_PAGE,
    REDIRECTED_TO_EXTERNAL_SYSTEM,
}
